### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Very1** [LixieWulf/Allure#19]
**OS:** IOS

**Build:** The most recent one

---

**Issue:** There is no modded tier 3 reconstructor

**Method(s) To Reproduce:** it’s just not there

**All Mods Used:** no other mods

**Crash Logs:** 

---

**Place an X in this box to show you understand.**

- [X ] **I have updated to the newest commit of Exotic Mod and the latest official release build of Mindustry to make sure this wasn't already fixed.**

**Comment by LixieWulf** [comment]
I haven't made all the tier 3 units yet. I'll leave this open for information until I make them.

**Comment by LixieWulf** [comment]
![Screenshot_20210822-040652](https://user-images.githubusercontent.com/61173114/130351916-d64f587e-1fd5-4c21-89c0-ede8a87655d7.png)
