### ISSUE TITLE
The ultimate launch pad and blue wolframite conduit is broken 

### ISSUE THREAD

**Issue by sirgamesalot010** [LixieWulf/Allure#2]
Once I place the ultimate launch pad it duplicates itself and is unremoveable for the blue wolframite conduit it just doesn't do anything except stay in one place forever

**Comment by LixieWulf** [comment]
i never did fix that did i

**Comment by K103908** [comment]
The ultimate launch pad can't be fixed as it no longer has a use in mindustry. The conduit will be worked on however.
