### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NeonSupernova** [LixieWulf/Allure#38]
**OS:** *iOS*

**Build:** *130*

---

**Issue:** *Not sure if it's a bug or unfinished, but infini
![image](https://user-images.githubusercontent.com/78397254/130366764-1006ee2e-875f-4a62-9104-e8cd0c33c5a5.png) and prominence ![image](https://user-images.githubusercontent.com/78397254/130366782-6d42ba19-c8c0-451a-a4ea-577ca4f15714.png)
do not show properly, and the extractor sprite does not show properly in the build menu![image](https://user-images.githubusercontent.com/78397254/130366817-79e49a6b-3c4c-420e-9309-af8f571c0811.png)*

**Method(s) To Reproduce:** *I loaded up a a fresh instance of Mindustry, and tested the mod. Just came across them.*

**All Mods Used:** *Exotic is the only mod used*

**Crash Logs:** *If you experienced a crash, put the logs here. Otherwise this line can be left alone.*

---

**Place an X in this box to show you understand.**

- [x] **I have updated to the newest commit of Exotic Mod and the latest official release build of Mindustry to make sure this wasn't already fixed.**

**Comment by LixieWulf** [comment]
Report the Extractor bug to Anuke, not me. It is not a bug with Exotic.
Infini and prominence are very unfinished, and I will eventually fix that. (when I stop procrastinating)
