### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Dude-324** [LixieWulf/Allure#4]
**OS:** *The operating system used, such as iOS or Windows.*
win 10
**Build:** *The current build number you are on.*
v124
---

**Issue:** *Explain the issue you have here. Please be as descriptive as possible and leave a video or screenshot if possible.*
using the bakesale-barrage at all makes the game stop responding regardless of ammo, amount of ammo or the presence of overdrives
**Method(s) To Reproduce:** *How you ran across this issue, and how I am supposed to recreate it.*
i ran across this issue while testing out the turrets in the mod and you can recreate it by putting ammo into the bakesale-barrage and then firing it somehow, i tried it by possesing the turret and with logic but the issue would probably occur with enemies too
**All Mods Used:** *Link or put the zip files of all mods other than Exotic Mod used when this issue happened.*
at first i was using a few other mods but the issues persisted even when i only used exotic mod
**Crash Logs:** *If you experienced a crash, put the logs here. Otherwise this line can be left alone.*

---

**Place an X in this box to show you understand.**

- [ x] **I have updated to the newest commit of Exotic Mod and the latest official release build of Mindustry to make sure this wasn't already fixed.**

**Comment by LixieWulf** [comment]
it should be fixed now, turns out @MEEPofFaith is a big moron and forgot -1 drag works exactly like 1 drag.

**Comment by MEEPofFaith** [comment]
> it should be fixed now, turns out @MEEPofFaith is a big moron and forgot -1 drag works exactly like 1 drag.

That was before anuke made it actually do something.

**Comment by MEEPofFaith** [comment]
It's been negative drag since v5

**Comment by Dude-324** [comment]
thx, i wanted to see what the turret actually did
