### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NeonSupernova** [LixieWulf/Allure#40]
**OS:** *The operating system used, such as iOS or Windows.*
iOS
**Build:** *The current build number you are on.*
130.1
---

**Issue:** *Explain the issue you have here. Please be as descriptive as possible and leave a video or screenshot if possible.*
Neither item source allows to pick items whilst editing ingame
**Method(s) To Reproduce:** *How you ran across this issue, and how I am supposed to recreate it.*
Open a map in editor, edit in-game, place either item source, and neither should show anything but a black line
**All Mods Used:** *Link or put the zip files of all mods other than Exotic Mod used when this issue happened.*
Exotic 
**Crash Logs:** *If you experienced a crash, put the logs here. Otherwise this line can be left alone.*

---

**Place an X in this box to show you understand.**

- [x] **I have updated to the newest commit of Exotic Mod and the latest official release build of Mindustry to make sure this wasn't already fixed.**

**Comment by LixieWulf** [comment]
![Screenshot_20210831-120035](https://user-images.githubusercontent.com/61173114/131553091-c7e97f6f-4f36-4045-9b42-647487013999.png)
Cannot reproduce. Likely a game bug, if one at all.
