### ISSUE TITLE
Cannot load with version 6

### ISSUE THREAD

**Issue by star-krafter** [LixieWulf/Allure#49]
**OS:** *The operating system used, such as iOS or Windows and using bBuestacks.*

**Build:** *The current build number you are on.*

---

**Issue:** *Explain the issue you have here. Please be as descriptive as possible and leave a video or screenshot if possible.*

**Method(s) To Reproduce:** *How you ran across this issue, and how I am supposed to recreate it.*

**All Mods Used:** *Link or put the zip files of all mods other than Exotic Mod used when this issue happened.*

**Crash Logs:** *If you experienced a crash, put the logs here. Otherwise this line can be left alone.*

---

**Place an X in this box to show you understand.**

- [ ] **I have updated to the newest commit of Exotic Mod and the latest official release build of Mindustry to make sure this wasn't already fixed.**

Whenever I attempt to install the mod to Mindustry, the mod continues to come up with the same error "Requires min game version: 131." please help.

**Comment by LixieWulf** [comment]
Update to 7.0. If you require assistance, ask in the Mindustry discord.
