### ISSUE TITLE
Don`t start map.

### ISSUE THREAD

**Issue by Creater3d** [LixieWulf/Allure#55]
Don`t start map - push on button , but nothing.
![image](https://user-images.githubusercontent.com/73776761/166432081-a53f5094-2300-4315-b032-00cf8607d9a8.png)

**Comment by LixieWulf** [comment]
This does not work due to a game bug around reading sectors in 135. Update to BE or wait.

**Comment by Creater3d** [comment]
"BE" - what is it in text?
