### ISSUE TITLE
Incompatible with v7.136/137

### ISSUE THREAD

**Issue by qwertyuiop265000** [LixieWulf/Allure#59]
Android

v7.137
---

This mod is straight up incompatible with v7.136 and onward.

Launch the game with Exotic Mod enabled on v7.136 or later.

No Other Mods

---

- [ X] **I have updated to the newest commit of Exotic Mod and the latest official release build of Mindustry to make sure this wasn't already fixed.**

**Comment by LixieWulf** [comment]
0.8 branch exists btw
