### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by sXcybericX** [LixieWulf/Allure#63]
**OS:** iOS

**Build:** v0.7 

---

**Issue:** I can't start the mod. Writes what you need to change minGameVersion to 136 in mod.json

**Method(s) To Reproduce:** i will cahnge minGameVersion on 136 but mod crushed

**All Mods Used:** none

---

**Place an X in this box to show you understand.**

- [x] **I have updated to the newest commit of Exotic Mod and the latest official release build of Mindustry to make sure this wasn't already fixed.**

**Comment by LixieWulf** [comment]
Intentional. An update will be released when it is ready.
