### ISSUE TITLE
Spriting error

### ISSUE THREAD

**Issue by Hot-Sausage07** [LixieWulf/Allure#65]
**OS:** *Windows*

**Build:** *release build 144.3*

---

**Issue:** *Spriting error in Spatial Conduit. Physics Defined. Leaking tube*

**Method(s) To Reproduce:** *Foundly after just testing off, adjust something in sprite.*

**All Mods Used:** *(Not a Crash)(Disabled Cyber IO).*

**Crash Logs:** *Non Actually.*

---

**Place an X in this box to show you understand.**

- [x] **I have updated to the newest commit of Exotic Mod and the latest official release build of Mindustry to make sure this wasn't already fixed.**

![image](https://github.com/BlueWolf3682/Exotic-Mod/assets/78838382/a49582d6-58e0-4a9e-83a5-2aeee1a03b74)

**Comment by LixieWulf** [comment]
this is not something i want to bother fixing
[however, it appears anuke himself fixed it for me](https://github.com/Anuken/Mindustry/commit/5c178c20a1b73c0ec4e9dd3ee3a7a8aef4e4012a), so thats cool
