### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by littlekatter330** [LixieWulf/Allure#67]
Windows

146

---

content error

update the mod

---

**Place an X in this box to show you understand.**

- [x] **I have updated to the newest commit of Allure and the latest official release build of Mindustry to make sure this wasn't already fixed.**
![20231014215812_1](https://github.com/BlueWolf3682/Allure/assets/113895869/d6254683-133e-4b44-9d62-7a9b11ce625a)

**Comment by LixieWulf** [comment]
Logs.

**Comment by LixieWulf** [comment]
Figured it out, it's because of a bug with ShootSummon that has an unreleased fix. It'll go away if you use BE or once the next release of Mindustry goes out.
