### ISSUE TITLE
i can't find the planet

### ISSUE THREAD

**Issue by jehosula** [LixieWulf/Allure#68]
### Platforms

Android, Windows

### Mindustry Build

BE

### Mod Version

sorry to make a report but
mod browser verion would not be able to use the mod otherwise

### Issue

can't find planet

### Reproduction Method

have the mod and click the campain

### Save File

does not matter

### Game Logs

does not matter

### Le Checkboxe

- [X] I have disabled all other mods and reproduced this bug anyways.
- [X] I have updated to the latest release/BE (Bleeding Edge) version before submitting this report.
- [X] I have confirmed that this issue has not already been reported.

**Comment by LixieWulf** [comment]
Intentional. Read the mod description.

**Comment by jehosula** [comment]
wrong mod bruh
