### ISSUE TITLE
Rename the "hiusbgjdfv" effect in the temp-harmony unit to some other gibberish

### ISSUE THREAD

**Issue by vincenzoiscool** [LixieWulf/Allure#72]
### Platforms

Mac

### Mindustry Build

147

### Mod Version

spaghetti

### Issue

The "hiusbgjdfv" effect in the temp-harmony unit contradicts with the original harmony, so just rename it.

### Reproduction Method

it happens when you load the game with the mod

### Game Logs

check reproduction method

### Le Checkboxe

- [X] I have disabled all other mods and reproduced this bug anyways.
- [X] I have updated to the latest release/BE (Bleeding Edge) version before submitting this report.
- [X] I have confirmed that this issue has not already been reported.

**Comment by LixieWulf** [comment]
Fixed.

**Comment by vincenzoiscool** [comment]
cool
